/* Autogenerated with kurento-module-creator */

#ifndef __FACE_RECOGNITION_IMPL_FACTORY_HPP__
#define __FACE_RECOGNITION_IMPL_FACTORY_HPP__

#include "FaceRecognitionImpl.hpp"
#include "OpenCVFilterImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace facerecognition
{

class FaceRecognitionImplFactory : public virtual OpenCVFilterImplFactory
{
public:
  FaceRecognitionImplFactory() = default;

  std::string getName() const override {
    return "FaceRecognition";
  };

private:

  MediaObjectImpl *createObjectPointer (
      const boost::property_tree::ptree &conf,
      const Json::Value &params) const override;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline) const;
};

} /* facerecognition */
} /* module */
} /* kurento */

#endif /*  __FACE_RECOGNITION_IMPL_FACTORY_HPP__ */
