/* Autogenerated with kurento-module-creator */

#include "FaceRecognitionImpl.hpp"
#include "IdPerson.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{
namespace module
{
namespace facerecognition
{

void dummyFacerecognition ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<FaceRecognition> object;

    s.SerializeNVP (object);
  }
  {
    JsonSerializer s (true);
    std::shared_ptr<IdPerson> object;

    s.SerializeNVP (object);
  }
}

} /* facerecognition */
} /* module */
} /* kurento */
