/* Autogenerated with kurento-module-creator */

#ifndef __FACE_RECOGNITION_OPENCV_IMPL_HPP__
#define __FACE_RECOGNITION_OPENCV_IMPL_HPP__

#include <OpenCVProcess.hpp>
#include "FaceRecognition.hpp"
#include <EventHandler.hpp>

namespace kurento
{
namespace module
{
namespace facerecognition
{

class FaceRecognitionOpenCVImpl : public virtual OpenCVProcess
{

public:

  // TODO: Following is a kludge to get correct shared_from_this()
  //       from the ArMarkerdetectorImpl class inherited from this.
  virtual std::shared_ptr<MediaObject> getSharedFromThis()=0;

private:
  std::string path;
  int opFilter;
  std::string newPerson;

public:

  FaceRecognitionOpenCVImpl ();

  virtual ~FaceRecognitionOpenCVImpl() = default;

  virtual void process (cv::Mat &mat);

  void setConfig(const std::string &path, const int opFilter, const std::string &newPerson);

  sigc::signal<void, IdPerson> signalIdPerson;


};

} /* facerecognition */
} /* module */
} /* kurento */

#endif /*  __FACE_RECOGNITION_OPENCV_IMPL_HPP__ */
