/* Autogenerated with kurento-module-creator */

#include <iostream>
#include "FaceRecognitionInternal.hpp"
#include <KurentoException.hpp>
#include <jsonrpc/JsonSerializer.hpp>
#include "MediaPipeline.hpp"

namespace kurento
{
namespace module
{
namespace facerecognition
{

void FaceRecognitionMethodSetConfig::invoke (std::shared_ptr<FaceRecognition> obj)
{
  if (!obj) {
    throw KurentoException (MEDIA_OBJECT_NOT_FOUND, "Invalid object while invoking method FaceRecognition::setConfig");
  }

  return obj->setConfig (path, opFilter, newPerson);
}

void FaceRecognitionMethodSetConfig::Serialize (kurento::JsonSerializer &s)
{
  if (s.IsWriter) {
    s.SerializeNVP (path);

    s.SerializeNVP (opFilter);

    s.SerializeNVP (newPerson);

  } else {
    if (s.JsonValue.isNull ()) {
      throw KurentoException (MARSHALL_ERROR,
                              "'operationParams' is required");
    } else if (!s.JsonValue.isObject ()){
      throw KurentoException (MARSHALL_ERROR,
                              "'operationParams' should be an object");
    }

    if (!s.JsonValue.isMember ("path") || !s.JsonValue["path"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'path' parameter should be a string");
    }

    s.SerializeNVP (path);

    if (!s.JsonValue.isMember ("opFilter") || !s.JsonValue["opFilter"].isConvertibleTo (Json::ValueType::intValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'opFilter' parameter should be a integer");
    }

    s.SerializeNVP (opFilter);

    if (!s.JsonValue.isMember ("newPerson") || !s.JsonValue["newPerson"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'newPerson' parameter should be a string");
    }

    s.SerializeNVP (newPerson);

  }
}

std::shared_ptr<MediaPipeline> FaceRecognitionConstructor::getMediaPipeline ()
{
  return mediaPipeline;
}

void FaceRecognitionConstructor::Serialize (kurento::JsonSerializer &s)
{
  if (s.IsWriter) {
    s.SerializeNVP (mediaPipeline);

  } else {
    if (s.JsonValue.isNull ()) {
      throw KurentoException (MARSHALL_ERROR,
                              "'constructorParams' is required");
    } else if (!s.JsonValue.isObject ()){
      throw KurentoException (MARSHALL_ERROR,
                              "'constructorParams' should be an object");
    }

    if (!s.JsonValue.isMember ("mediaPipeline") || !s.JsonValue["mediaPipeline"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'mediaPipeline' parameter should be a string");
    }

    s.SerializeNVP (mediaPipeline);

  }
}

} /* facerecognition */
} /* module */
} /* kurento */
