/* Autogenerated with kurento-module-creator */

#ifndef __MASK_DETECTION_IMPL_HPP__
#define __MASK_DETECTION_IMPL_HPP__

#include "OpenCVFilterImpl.hpp"
#include "MaskDetection.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>
#include "MaskDetectionOpenCVImpl.hpp"

namespace kurento
{
namespace module
{
namespace maskdetection
{
class MaskDetectionImpl;
} /* maskdetection */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::maskdetection::MaskDetectionImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace maskdetection
{

class MaskDetectionImpl : public OpenCVFilterImpl, public virtual MaskDetection, public virtual MaskDetectionOpenCVImpl
{

private:
  std::string path;

public:

  MaskDetectionImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~MaskDetectionImpl() = default;

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

  virtual void setConfig(const std::string &path);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* maskdetection */
} /* module */
} /* kurento */

#endif /*  __MASK_DETECTION_IMPL_HPP__ */
