/* Autogenerated with kurento-module-creator */

#ifndef __MASK_DETECTION_OPENCV_IMPL_HPP__
#define __MASK_DETECTION_OPENCV_IMPL_HPP__

#include <OpenCVProcess.hpp>
#include "MaskDetection.hpp"
#include <EventHandler.hpp>

namespace kurento
{
namespace module
{
namespace maskdetection
{

class MaskDetectionOpenCVImpl : public virtual OpenCVProcess
{

private:
  std::string path;

public:

  MaskDetectionOpenCVImpl ();

  virtual ~MaskDetectionOpenCVImpl() = default;

  virtual void process (cv::Mat &mat);

  void setConfig(const std::string &path);

};

} /* maskdetection */
} /* module */
} /* kurento */

#endif /*  __MASK_DETECTION_OPENCV_IMPL_HPP__ */
