/* Autogenerated with kurento-module-creator */

#ifndef __MASK_DETECTION_OPENCV_IMPL_HPP__
#define __MASK_DETECTION_OPENCV_IMPL_HPP__

#include <OpenCVProcess.hpp>
#include "MaskDetection.hpp"
#include <EventHandler.hpp>

namespace kurento
{
namespace module
{
namespace maskdetection
{

class MaskDetectionOpenCVImpl : public virtual OpenCVProcess
{

public:

  // TODO: Following is a kludge to get correct shared_from_this()
  //       from the ArMarkerdetectorImpl class inherited from this.
  virtual std::shared_ptr<MediaObject> getSharedFromThis()=0;

private:
  std::string path;

public:

  MaskDetectionOpenCVImpl ();

  virtual ~MaskDetectionOpenCVImpl() = default;

  virtual void process (cv::Mat &mat);

  void setConfig(const std::string &path);

  sigc::signal<void, MaskDetected> signalMaskDetected;

};

} /* maskdetection */
} /* module */
} /* kurento */

#endif /*  __MASK_DETECTION_OPENCV_IMPL_HPP__ */
