/* Autogenerated with kurento-module-creator */

#ifndef __FACE_RECOGNITION_INTERNAL_HPP__
#define __FACE_RECOGNITION_INTERNAL_HPP__

#include "FaceRecognition.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace facerecognition
{

class FaceRecognitionMethodSetConfig
{
public:
  FaceRecognitionMethodSetConfig() = default;
  ~FaceRecognitionMethodSetConfig() = default;

  void invoke (std::shared_ptr<FaceRecognition> obj);
  void Serialize (JsonSerializer &serializer);

  std::string getPath () {
    return path;
  }

  void setPath (const std::string &path) {
    this->path = path;
  }

  int getOpFilter () {
    return opFilter;
  }

  void setOpFilter (int opFilter) {
    this->opFilter = opFilter;
  }

  std::string getNewPerson () {
    return newPerson;
  }

  void setNewPerson (const std::string &newPerson) {
    this->newPerson = newPerson;
  }

private:
  std::string path;
  int opFilter;
  std::string newPerson;
};

class FaceRecognitionConstructor
{
public:
  FaceRecognitionConstructor() = default;
  ~FaceRecognitionConstructor() = default;

  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<MediaPipeline> getMediaPipeline ();

  void setMediaPipeline (std::shared_ptr<MediaPipeline> mediaPipeline) {
    this->mediaPipeline = mediaPipeline;
  }

private:
  std::shared_ptr<MediaPipeline> mediaPipeline;
};

} /* facerecognition */
} /* module */
} /* kurento */

#endif /*  __FACE_RECOGNITION_INTERNAL_HPP__ */
