/* Autogenerated with kurento-module-creator */

#include "IdPerson.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <ctime>
#include <string>

namespace kurento
{
namespace module
{
namespace facerecognition
{

void
IdPerson::Serialize (JsonSerializer &s)
{
  Media::Serialize (s);

  s.SerializeNVP (idPerson);
}

} /* facerecognition */
} /* module */
} /* kurento */

namespace kurento
{

void Serialize (std::shared_ptr<kurento::module::facerecognition::IdPerson> &event, JsonSerializer &s)
{
  if (!s.IsWriter && !event) {
    event.reset (new kurento::module::facerecognition::IdPerson() );
  }

  if (event) {
    event->Serialize (s);
  }
}

} /* kurento */
