/* Autogenerated with kurento-module-creator */

#ifndef __ID_PERSON_HPP__
#define __ID_PERSON_HPP__

#include <json/json.h>
#include <memory>
#include "Media.hpp"

namespace kurento
{
namespace module
{
namespace facerecognition
{
class IdPerson;
} /* facerecognition */
} /* module */
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::module::facerecognition::IdPerson> &object, JsonSerializer &s);
}


namespace kurento
{
namespace module
{
namespace facerecognition
{

class IdPerson : public Media
{

public:

  IdPerson (std::shared_ptr<MediaObject> source, const std::string &type, const std::string &idPerson) : Media (source, type) {
      this->idPerson = idPerson;
  };

  IdPerson (const IdPerson &copy) : Media (copy) {
      this->idPerson = copy.idPerson;
  };

  IdPerson (const Json::Value &value);

  virtual void setIdPerson (const std::string &idPerson) {
    this->idPerson = idPerson;
  };

  virtual const std::string &getIdPerson () {
    return idPerson;
  };

  static std::string getName() {
    return "IdPerson";
  }

  void Serialize (JsonSerializer &s) override;

protected:

  IdPerson() = default;

private:
  std::string idPerson;

  friend void kurento::Serialize (std::shared_ptr<kurento::module::facerecognition::IdPerson> &event, JsonSerializer &s);
};

} /* facerecognition */
} /* module */
} /* kurento */

#endif /*  __ID_PERSON_HPP__ */
